project:
  type: book

book:
  title: |
    ERAHUMED DSS: a decision support system for the environmental risk
    assessment of pesticide management practices in Mediterranean wetlands
  author:
    - name: Valerio Gherardi
      orcid: 0000-0002-8215-3013
      email: vgherard840@gmail.com
      corresponding: true
    - name: Pablo Amador Crespo
      orcid: 0000-0002-3793-8794
      email: pamadorc@gmail.com
    - name: Andreu Rico
      orcid: 0000-0002-1820-4218
  description: |
    The ERAHUMED Decision Support System: Software Manual and Technical
    Documentation.
  cover-image: cover.png
# favicon: images/cover-2e-small.png

  chapters:
  - index.qmd
  - chapters/intro.qmd
  - chapters/birdseye.qmd
  - chapters/model-inputs.qmd
  - chapters/rfms.qmd
  - chapters/hydrology.qmd
  - chapters/exposure.qmd
  - chapters/risk.qmd
  - chapters/erahumed_dss_ui.qmd
  - chapters/erahumed_dss_pkg.qmd
  - chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

