project:
  type: book

book:
  title: "ERAHUMED DSS"
  author: "Valerio Gherardi"
  description: |
    The ERAHUMED Decision Support System: Software Manual and Technical
    Documentation.
# cover-image: images/cover-2e-small.png
# favicon: images/cover-2e-small.png

  chapters:
  - index.qmd
  - intro.qmd

  - part: Technical description
    chapters:
    - hydrological_balance.qmd

  - part: User Manual
    chapters:
    - erahumed_dss_ui.qmd
    - erahumed_dss_pkg.qmd

  - references.qmd

  appendices:
    - appendix.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

