project:
  type: book

book:
  title: "ERAHUMED DSS"
  author:
    - name: Valerio Gherardi
      orcid: 0000-0002-8215-3013
      email: vgherard840@gmail.com
      corresponding: true
    - name: Pablo Amador Crespo
      orcid: 0000-0002-3793-8794
      email: pamadorc@gmail.com
  description: |
    The ERAHUMED Decision Support System: Software Manual and Technical
    Documentation.
  cover-image: cover.png
# favicon: images/cover-2e-small.png

  chapters:
  - index.qmd
  - intro.qmd

  - part: Technical description
    chapters:
    - hydrological_balance.qmd

  - part: User Manual
    chapters:
    - erahumed_dss_ui.qmd
    - erahumed_dss_pkg.qmd

  - references.qmd

  appendices:
    - input_data.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

