# ERAHUMED simulation layers

This Chapter provides detailed descriptions of the various layers of the ERAHUMED simulation chain, briefly introduced in @sec-birds-eye-view.

## INP: Input Data {#sec-inp}

The purpose of this layer is simply to collect the empirical data that provides the observational input to all subsequent simulation layers. This data consists of hydrological and meteorological time series data for the Albufera lake in the desired time frame.

### Input

The only inputs to this layer are the two aforementioned time-series data-sets.

Hydrological data consists of the direct measurements of the Albufera lake's daily water levels and outflows. Since the lake has three estuaries (*Gola de Pujol*, *Gola del Perellonet* and *Gola del Perelló*), this data amounts to four daily time series. The actual dataset bundled with the ERAHUMED software was obtained from the public data repository compiled by the *Confederación Hidrográfica del Júcar* (TODO: Ref.), and is described in more detail in [Appendix @sec-data-hydro].

Meteorological data consists of the daily measurements of precipitation and evapotranspiration per unit are, and temperature (average, maximum and minimum). This amounts to five daily the series. The actual data bundled with the ERAHUMED software was obtained (TODO: where), and is described in more detail in [Appendix @sec-data-meteo].

The time-series inputs described above are collected in the table below (the common index $t$ refers to the time - *i.e.* day - of observation).

| Input                     | Units        | Description                        |
|---------------------------|--------------|------------------------------------|
| $L_t$                     | $\text{m}$   | Lake water level                   |
| $O_t^{\text{Pujol}}$      | $\text{m}^3$ | *Pujol* daily outflow              |
| $O_t^{\text{Perelló}}$    | $\text{m}^3$ | *Perelló* daily outflow            |
| $O_t^{\text{Perellonet}}$ | $\text{m}^3$ | *Perellonet* daily outflow         |
| $\text{P}_t$              | $\text{mm}$  | Precipitation (per unit area)      |
| $\text{ETP}_t$            | $\text{mm}$  | Evapotranspiration (per unit area) |
| $T_t^{\text{max}}$        | $\text{°C}$  | Maximum temperature                |
| $T_t^{\text{min}}$        | $\text{°C}$  | Minimum temperature                |
| $T_t^{\text{ave}}$        | $\text{°C}$  | Average temperature                |

: Observational input to the ERAHUMED simulation (INP layer). {#tbl-inp-time-series}

### Output

This layer does not involve any actual computation, and its output is simply a time-series data-set obtained as the combination of the two input data-sets, *i.e.* the collection of time series of @tbl-inp-time-series.

## HBA: Hydrological Balance of the Albufera lake {#sec-hba}

The purpose of this layer is to compute the total daily inflow to the Albufera lake. The relevant equation expressing the hydrological balance is:

$$
\text{Volume Change} = \text{Inflow} - \text{Outflow} + \text{Precipitation} - \text{Evapotranspiration}
$$ {#eq-hydro-balance-symbolic}

where the unknown is $\text{Inflow}$, whereas the remaining terms are obtained from observational data, as described in the previous Section (@sec-inp).

### Input

The inputs specific to this layer are two numerical functions converting water heights into the water *volumes* that appear in @eq-hydro-balance-symbolic. Specifically:

-   The lake's *storage curve* converts the measured lake's level into a total water volume.
-   The *precipitation-evapotranspiration volume function* (or, for the sake of brevity, *P-ETP function*), that converts precipitation and evapotranspiration values *per unit area* into an overall water volume difference.

Even though the R interface to the ERAHUMED software allows arbitrary definitions, the graphical user interface assumes a linear approximation for both these functions. Therefore, the storage curve is assumed to take the form:

$$
V_t = m \cdot L_t + q,
$$ {#eq-storage-function} where $V_t$ is the (daily) water volume of the lake, $L_t$ the corresponding water level (*cf.* @tbl-inp-time-series), and $m$ and $q$ are numerical coefficients[^simulation_layers-1]. Correspondingly, the P-ETP function reads:

[^simulation_layers-1]: In fact, for the purpose of computing volume *changes* entering the hydrological balance @eq-hydro-balance-symbolic, only the slope $m$ is required.

$$
\Delta V_t ^{\text{P-ETP}} = \alpha \cdot \text{P}_t - \beta\cdot \text{ETP}_t,
$$ {#eq-petp-function} where the left-hand side represents the relevant water volume difference, whereas the $\text{P}$ and $\text{ETP}$ terms in the right-hand side are the measured precipitation and evapotranspiration levels per unit area (*cf.* @tbl-inp-time-series). The actual default values of $m$, $q$, $\alpha$ and $\beta$ are documented in [Appendix @sec-storage-curve].

### Output

The output of this layer consists of the time-series collected in the table below.

| Variable | Units        | Description        |
|----------|--------------|--------------------|
| $V_t$    | $\text{m}^3$ | Lake water volume  |
| $I_t$    | $\text{m}^3$ | Lake total inflow  |
| $O_t$    | $\text{m}^3$ | Lake total outflow |

: HBA layer outputs {#tbl-hba-output}

### Details

Using the notation introduced in the previous Subsections, we can rewrite @eq-hydro-balance-symbolic as follows:

$$
V_{t+1} - V_t = I_t -O_t +\Delta V^{\text {ETP}}_t,
$$ {#eq-hydro-balance-explicit}

where $V_t$ and $\Delta V^{\text {ETP}}_t$ are computed through the storage and P-ETP functions, as in Eqs. [-@eq-storage-function] and [-@eq-petp-function]. The only terms that requires further clarification in @eq-hydro-balance-explicit is $O_t$, the total outflow from the lake.

Strictly speaking, $O_t$ is not merely the sum of $O_t^{\text{Pujol}}$, $O_t^{\text{Perelló}}$ and $O_t^{\text{Perellonet}}$, but is rather calculated as follows:

$$
O_t = \max
\left[
O_t^{\text{Pujol}} + O_t^{\text{Perelló}} + O_t^{\text{Perellonet}},\, 
\Delta V^{\text {ETP}}_t+V_t-V_{t+1}
\right].
$$ {#eq-total-outflow}

The rationale is that the simple sum of estuaries outflows omits potentially important contributions from *water recirculation*, that is to say, water being pumped out from the lake for rice-field irrigation, by the so-called *tancats*. Such amount of recirculated water is hard to estimate and, in the lack of a better model, we simply assume this to be negligible, *except* when a positive amount is required by @eq-hydro-balance-explicit itself, due the physical constraint that $I_t \geq 0$.

Once $O_t$ is calculated through @eq-total-outflow, $I_t$ can be immediately obtained from @eq-hydro-balance-explicit. Notice that whenever the aforementioned compensating outflow term due to water recirculation is included (which happens when the maximum in Eq. [-@eq-total-outflow] is given by the second term), the total inflow is always estimated to be zero.

## HBP: Hydrological Balance of rice Paddy clusters {#sec-hbp}

This layer simulates the local hydrology (*i.e.* water levels, inflows and outflows) of rice paddy clusters in the Albufera Natural Park. The simulation, that literally involves the generation of a synthetic data-set, is based on:

-   The hydrology of the Albufera lake, which allows to constrain the total outflow of all rice paddies, assumed to be less than or equal to the lake's total inflow (the main output of the HBA layer, see @sec-hba).
-   An estimate of the fraction of the total lake's inflow that comes from each of the 26 ditches that flow into the Albufera.
-   A subdivision of the rice fields surface into clusters that are assumed to drain water into a single ditch - meaning that the sum of outflows of clusters from the same group must be less than or equal to the total flow through the corresponding ditch.
-   An ideal yearly management plan for the irrigation and draining of rice paddies.

### Input {#sec-hbp-input}

As already mentioned, the simulation is based on a spatial clustering, which is described in greater detail in [Appendix @sec-data-rice-clusters]. In particular each cluster is labeled according to its rice variety, and to its field type (*tancat* or regular field), which we will indicate in the following through the categorical variables $v = \text{Clearfield, Sendra or Bomba}$ and $\theta =\text{Tancat, Regular}$ respectively.

The yearly management plan for these clusters, is described in [Appendix @sec-data-albufera-management], and provides, for each day of the year $d$, rice variety $v$ and field type $\theta$ the following:

-   $\text{Ir}_{d,v,\theta}$: boolean expressing whether the cluster is supposed to be irrigated (if true) on day of year $d$.
-   $\text{Dr}_{d,v,\theta}$: boolean expressing whether the cluster is supposed to be drained (if true) on day of year $d$.
-   $\mathcal H _{d,v,\theta}$: ideal water level (in $\text{cm}$) of the cluster on day of year $d$.

We stress that the values of these yearly series are specific to each rice variety and field type, and the corresponding values for a cluster are obtained by matching with the corresponding cluster's attributes.

In addition to these rather complex input, the layer requires the following numerical parameters:

-   $k_\text{flow}$ (*Ideal flow rate*). Rate at which water flows through rice paddies when these are being simultaneously irrigated and drained, with the overall level being kept constant. Expressed in $\text{cm}\cdot\text{day}^{-1}$.

-   $h_{\text{thres}}$ (*Height threshold*). Maximum allowed water level for a cluster to be considered emptied, used in the calculation of draining/irrigation plan delays. Expressed in $\text{cm}$.

-   $\text{seed}$ The seed passed to the random number generator involved in the permutation of clusters described below. Clearly, this parameter is of no physical consequence, its main purpose being to ensure the exact reproducibility of simulations.

Finally, it should be noted that the simulation involves random sampling (see [Subsection @sec-hbp-details]), so that the seed of random number generation is an additional pseudo-parameter.

### Output

The output of this layer provides a simulation for the local hydrology of each cluster, summarized by the variables in the table below, in which the indices $c$ and $t$ refer to cluster and time, respectively.

| Variable  | Units        | Description            |
|-----------|--------------|------------------------|
| $V_{c,t}$ | $\text{m}^3$ | Cluster's water volume |
| $I_{c,t}$ | $\text{m}^3$ | Cluster's inflow       |
| $O_{c,t}$ | $\text{m}^3$ | Cluster's outflow      |

: HBP layer outputs. {#tbl-hbp-output}

### Detail {#sec-hbp-details}

In the notation introduced above, the purpose of this layer is to simulate for each cluster $c$ the hydrological time series of @tbl-hbp-output, satisfying the hydrological balance:

$$
V_{c,t+1}-V_{c,t} = I_{c,t}-O_{c,t} + (\text{P}_t-\text{ETP}_t)\times A_c
$$ {#eq-hbp-balance}

where $\text{P}_t$ and $\text{ETP}_t$ stand for precipitation and evapotranspiration per unit area, as in table @tbl-inp-time-series, whereas $A_c$ denotes the cluster's area. As mentioned in the introduction to this Section (see [-@sec-hbp]), this simulation rests on various simplifications, which we detail in what follows.

To begin with, we assume that each cluster only drains water into a single one out of the twenty-six main ditches that cross the Albufera Natural Park. In what follows, we will focus on the set of all clusters connected with a given ditch, and we will enumerate clusters through the index $c = 1,\,2,\,\dots,\,N_C$. On the other hand, clusters are assumed to be irrigated from the external of the Albufera system, *i.e.* not through any of the ditches which eventually flow into the lake.

These two assumptions imply that the sum of cluster outflows is constrained by:

$$
\sum _{c = 1} ^ {N_C} O_{c,t} \leq Q_t
$$ {#eq-sum-outflows-constraint}

where $Q_t$ denotes the daily flow through the ditch. This quantity is, in turn, not measured, and we estimate it through the following simple model:

$$
Q_t = \frac{\text{Area of clusters draining into ditch}}{\text{Area of all clusters}} \times \text{Lake's Inflow}_t
$$ {#eq-ditch-inflow}

where the lake's inflow is the one computed by the HBA layer (see @sec-hba).

Qualitatively speaking, the simulation works by finding daily values of $I_{c,t}$ and $O_{c,t}$ compatible with Eqs. [-@eq-hbp-balance] and [-@eq-sum-outflows-constraint], and such that the resulting hydrology is as close as possible with the "ideal" one prescribed by the specified management plan. This is accomplished in three steps:

1.  Computing ideal inflows and outflows, given current water levels and management plans.
2.  Computing actual inflows and outflows, and corresponding actual water level changes.\
3.  Computing required management plan delays, if some clusters were scheduled to be drained, but could not due to insufficient flow through the common ditch (see below for details).

These steps are iterated on a daily basis, starting from some initial time (say $t = 0$) at which all cluster water levels coincide with the ideal ones, and no plan delays are present.

Concerning the last step, a few words may serve to clarify the algorithm described below. The purpose of plan delays is to ensure that during each year's sowing season, all cluster's are emptied at some point, as required for ground\
applications of chemicals (modeled in subsequent layers of ERAHUMED). This is achieved by delaying by one day the management plan, whenever an emptying condition is not met. When far outside of the sowing window, the delays are reset then to zero, in order to ensure that delays are not carried over indefinitely, which would be quite unrealistic.

In what follows, the conversion between cluster water volumes and depths is provided by $V_{c,t} = A_c \cdot h_{c,t}$, and we denote by $\delta_{c,t}$ the time-series of plan delays for cluster $c$, which is initialized by $\delta_{c,0} =0$.

#### Step 1: ideal balance

Ideal balance quantities for each cluster $c$ are obtained from the management plan data-set, whose relevant row is identified by the cluster's rice variety $v$ and field type $\theta$, and the delayed day:

$$
d_{c,t+1} = d_{t+1}-\delta_{c,t},
$$ {#eq-hbp-delayed-day}

where $d_{t+1}$ denotes the day of year corresponding to time $t+1$, and $\delta_{c,t}$ the accumulated plan delay.

Let $h _{c,t+1}^{\text{id}}$ denote the ideal depth for cluster $c$ at time $t+1$ retrieved in this way, and $\text{Ir}_{c,t}$, $\text{Dr}_{c,t}$ the corresponding ideal irrigation and draining plans. Furthermore, denote by $V_{c,t+1}^{\text{id}} = A_c \cdot h_{c,t+1}^{\text{id}}$ the corresponding ideal water volume.

In order to compute ideal inflow and outflow, we require (*cf.* @eq-hbp-balance):

$$
V_{c,t+1}^{\text{id}} = \max \lbrace V_{c,t}^{\text{id}}  + (\text{P}_t-\text{ETP}_t)\times A_c,0 \rbrace + I_{c,t}^{\text{id}}-O_{c,t}^{\text{id}}
$$ {#eq-hbp-balance-ideal}

Clearly, @eq-hbp-balance-ideal alone does not individually specify $I_{c,t}^{\text{id}}$ and $O_{c,t}^{\text{id}}$, but only their difference $\Delta _{c,t}^{\text{id}}= I_{c,t}^{\text{id}}-O_{c,t}^{\text{id}}$. In order to fix both these quantities:

$$
\begin{split}
(I_{c,t} ^\text{id})^{(0)}&= \begin{cases}
  k_\text{flow}  & \text{if }\text{Ir}_{c,t} = \text{Dr}_{c,t} = 1 \\
  0 & \text{otherwise}
\end{cases},\\
(O_{c,t} ^\text{id})^{(0)}&=(I_{c,t} ^\text{id})^{(0)}-\Delta _{c,t}^{\text{id}}.
\end{split}
$$ {#eq-hbp-id-flows-zero}

and, in order to ensure that flows are positive, we finally set:

$$
\begin{split}
O_{c,t} ^\text{id} &= \max\lbrace(O_{c,t} ^\text{id})^{(0)},\,0\rbrace\\
I_{c,t} ^\text{id} &= O_{c,t} ^\text{id} + \Delta _{c,t}^{\text{id}},
\end{split}
$$ {#eq-hbp-id-flows}

which satisfy @eq-hbp-balance-ideal and give rise to positive \^ $O_{c,t}^\text{id}$ and $I_{c,t}^\text{id}$.

#### Step 2: real balance

At each time-step $t$, the cluster's index set is randomly permuted [^simulation_layers-2], and the real flows are calculated as:

[^simulation_layers-2]: With some abuse of notation, we assume the indexes $c$ and $c'$ in @eq-hbp-real-flows to be sorted according to this random permutation.

$$
\begin{split}
O_{c,t} &= \min \lbrace O_{c,t}^\text{id},\,Q_t-\sum_{c'<c}O_{c',t} \rbrace ,\\
I_{c,t} &= \max\lbrace I_{c,t}^\text{id}-O_{c,t}^\text{id} + O_{c,t},\,0 \rbrace
\end{split}
$$ {#eq-hbp-real-flows}

In simple terms, clusters are emptied in a random order within the allowed capacity of the corresponding ditch. Using @eq-hbp-real-flows, we finally determine the real water level achieved as:

$$
V_{c,t+1} = \max \lbrace V_{c,t}  + (\text{P}_t-\text{ETP}_t)\times A_c,0 \rbrace + I_{c,t}-O_{c,t}
$$ {#eq-hbp-balance-real}

to be compared with @eq-hbp-balance-ideal.

#### Step 3: updating the plan delay

The updated value $\delta _{c,t+1}$ is obtained as follows. If $d_{t+1}$ (the *actual* day of year) is outside of the window $W = [\text{20th of April},\,\text{15th of October}]$, then $\delta_{c,t+1} = 0$. Otherwise, if $h_{c,t}^\text{id} > 0$ or $h_{c,t} < h_{\text{thres}}$, the plan delay is unchanged: $\delta_{c,t+1} = \delta_{c,t}$. Finally, if $h_{c,t}^\text{id} = 0$ but $h_{c,t} > h_{\text{thres}}$, we add one day of delay: $\delta_{c,t+1} = \delta_{c,t}+1$.

## CA: Chemical Applications

This simulation layer describes the application of chemicals to rice fields based on the simulated hydrology computed in the previous layer (@sec-hbp).

### Input

TBD.

### Output

TBD.

### Details

As described above, each application has a scheduled date $D$ and is either of "aerial" or "ground" type. In order to determine the actual application date, we proceed as follows:

1.  For ground applications, we select only those days in which both $\text{Ir}_{c,t} = \text{Dr}_{c,t} = 0$, where $\text{Ir}_{c,t}$ and $\text{Dr}_{c,t}$ are the true (in contrast to ideal) irrigation and draining states time-series described after @eq-hbp-delayed-day. Similarly, for aerial applications, we select days according to $\text{Ir}_{c,t} = \text{Dr}_{c,t} = 1$.

2.  For ground applications, out of the days selected in the previous step, we select the subset for which clusters' simulated water levels satisfy $h_{c,t} < h_{\text{thres}}$, where $h_{\text{thres}}$ is the same threshold used by the HBP layer (see @sec-hbp-input). For aerial applications, there is no corresponding constraint applied in this step.

3.  Out of the days selected in the previous step, we select the subset of days that are at least five days away from other applications of the same chemical.

4.  Finally, from the list of days resulting from all the above steps, we pick the single day for which the *delayed day* defined by @eq-hbp-delayed-day is as close as possible to $D$.

These steps are meant to be repeated for all subsequent applications of a given chemical in a given cluster. It is worth to notice that the algorithm for simulating clusters' hydrological balance described in @sec-hbp guarantees that the list of candidate days for application surviving until the final step above is non-empty.

## CT: Chemical Transport

This layer describes the evolution of chemical masses in the three compartments of foliage, water and sediment. This is obtained by solving the system of differential equations that describes the dynamics of chemicals, through a semi-analytic approach with suitable approximations and simplifications.

### Input

TBD.

### Output

TBD.

### Details

The evolution of masses in the foliage, water and sediment compartments is described by the following system of differential equations:

$$
\begin{split}
\dfrac{\text d{m}_f}{\text d t} & = -(k_f+w)m_f+a_f\\
\dfrac{\text d{m}_w}{\text d t} & = -(k_w+d_w+s+\frac{O}{V})m_w+d_sm_s+wm_f+a_w-\sigma(\frac{m_w}{\rho V}) \\
\dfrac{\text d{m}_s}{\text d t} & = (d_w+s)m_w-(k_s+d_s)m_s+a_s+\sigma(\frac{m_w}{\rho V})
\end{split}
$$ {#eq-ct-ode}

where:

-   $a_{f,w,s}$ are the mass application rates of the chemical in the three compartments,
-   $k_{f,w,s}$ are the degradation rates of the chemical in the three compartments,
-   $d_w$ and $d_s$ are the water-sediment diffusion rates,
-   $s$ is the settling rate,
-   $w$ is the washout rate,
-   $O$ is the outflow rate of the rice field,
-   $V$ is the volume of water in the rice field,
-   $\rho$ is the chemical solubility in water,
-   $\sigma(x)$ is a function (not further specified, see below) that grows quickly for $x > 1$, and vanishes for $x \leq 1$. This function accounts for solubility. (TODO: motivate the inclusion of exactly these processes)

Strictly speaking, all these terms have instantaneous time dependence[^simulation_layers-3]. Apart from making the [system @eq-ct-ode] hard to attack by analytic means, such a dependence is troubling because we don't have access to the exact time dependence of the majority of these terms (*e.g.* outflow, volume or chemical applications), our input consisting of simple daily average/cumulative values. On the other hand, if all the terms were constant, and if we could neglect $\sigma$, the solution of @eq-ct-ode would be immediate, as the corresponding system becomes a linear ODE with constant coefficients, in addition whose eigenvalues and eigenvectors can be computed explicitly.

[^simulation_layers-3]:  This observation also includes pure physico-chemical "constants" such as degradation rates, where the time dependence would stem from *temperature* dependence.

What we use in practice is an intermediate semi-analytic approach that allows us to compute daily values of $m_{f,w,s}$, which we can briefly summarize as follows. The time evolution of $m_{f,w,s}$ in a daily time-step (from $t$ to $t+1$, say, assuming $t$ is measured in days) is obtained through the following four consecutive stages:

1.  We compute the exact evolution of $m_{f,w,s}$ according to the linear ODE obtained by disregarding the processes of outflow, chemical application and solubility, and using daily constant values for all the remaining constants involved (described in more detail below).
2.  We compute the $m_w$ losses due to outflow as if they happened instantaneously after the processes computed in the previous step took place, with the water volume of the rice paddy varying from $V(t)+O(t)$ to $V(t)$[^simulation_layers-4]\
3.  We compute the mass applications again as instantaneous, after the losses in the water compartment due to outflows took place.
4.  We compare the resulting $m_w$ with the maximum amount allowed by the solubility in water, that is $m_w ^{\text{max}}(t) = \rho V(t)$ and transfer any excess to the sediment compartment ($m_s$).

[^simulation_layers-4]:  Recall that, in the notation of TODO, $V(t)$ denotes the final volume on day $t$.

In the following, we describe in full detail the computations involved in these four steps.

#### Step 1: linear ODE evolution (physico-chemical processes)

Disregarding outflow, mass application and solubility, we get a linear ODE of the form:

$$
\begin{split}
\dfrac{\text d{m}_f}{\text d t} & = \gamma m_f,\\
\dfrac{\text d{m}_w}{\text d t} & = a_{ww} m_w+a_{ws}m_s + w m_f, \\
\dfrac{\text d{m}_s}{\text d t} & = a_{sw}m_w+a_{ss}m_s,
\end{split}
$$ {#eq-ct-ode-linear}

with:

$$
\begin{split}
\gamma                  &= -(k_f + w),\\
a_{ww}                  &= - (k_w + d_ w +s)\\
a_{ws}                  &= d_s\\
a_{sw}                  &= d_w+s\\
a_{ss}                  &= -(k_s+d_s)
\end{split}
$$ {#eq-ct-ode-linear-coeffs}

where the various physico-chemical parameters are assumed to be constant during a daily time-step (see Sec. TODO for the actual numerical values).

The evolution of $m_f$ is easily obtained:

$$
m_f(t) = e^{\gamma t}m_f(0).
$$ {#eq-mf-evolution}

Plugging this into the three-dimensional system [-@eq-ct-ode-linear] we obtain a reduced two-dimensional system for the water-sediment compartments:

$$
\begin{split}
\dfrac{\text d{m}_w}{\text d t} & = a_{ww} m_w+a_{ws}m_s + w e ^{\gamma t}m_f(0), \\
\dfrac{\text d{m}_s}{\text d t} & = a_{sw}m_w+a_{ss}m_s,
\end{split}
$$ {#eq-ct-ode-linear-reduced}

which is solved explicitly with standard methods[^simulation_layers-5].

[^simulation_layers-5]: Letting $x = (m_w,\,m_s)^T$ and $b = w(m_f(0),0)^T$, the system can be rewritten in the form: $$ \dot x = Ax + e^{\gamma t }b $$ where $$ A = \begin{pmatrix} a_{ww} & a_{ws} \\ a_{sw} & a_{ss} \end{pmatrix} $$ The general solution reads: $$
      x(t) = e^{At}x(0)+(e^{At}-e^{\gamma t}I)(A-\gamma I)^{-1}b
      $$ where $I$ is the identity matrix. Notice that the exponential can be computed explicitly from the eigenvalues of $A$: $$
      e^{At} = e^{\lambda _+ t} P_+ + e^{\lambda _- t} P_-,
      $$ with: $$
      \lambda _{\pm} = \frac{\text{Tr}A}{2} \sqrt{\left(\frac{\text{Tr}A}{2}\right)^2 - \det A}
      $$ and $$
      P_{\pm} = \pm \frac{1}{\lambda _+ - \lambda _-}(A-\lambda _{\mp})
      $$

#### Step 2: mass losses due to outflow

Mass losses due to outflow are computed as if the outflow process happened instantaneously after the processes discussed in the previous step took place. The amount of mass in the water compartment is affected as follows:

$$
m_w \to \frac{V_f}{V_i} m_w,
$$ {#eq-mw-outflow}

where $V_i$ and $V_f$ denote the initial and final volume for the outflow process. We assume that $V_f$ coincides with the value $V(t)$ simulated by the HBP simulation layer (*cf.* Sec TODO), so that $V_i = V(t) + O(t)$, where $O(t)$ denotes the total simulated outflow for day $t$.

#### Step 3: chemical applications

Applications are computed as instantaneous and subsequent to outflow. Masses in the various compartments ($i = f,\,w,\,s$) are modified as follows:

$$
m_i \to m_i + a_i
$$ {#eq-mi-application}

#### Step 4: solubility

The chemical density in the water compartment after Steps 1, 2, and 3 is eventually compared with the chemical's solubility $\rho$, and any mass excess is instantaneously transferred to the sediment compartment. This implies the following modifications:

$$
m_s \to m_s + \max(0, \,m_w - \rho V),\quad m_w\to\max(m_w,\,\rho V),
$$ {#eq-m-solubility}

where, for the volume $V$ we again use the value $V(t)$ simulated by the HBP simulation layer.
